---
- hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
  
    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Install calico pod network
      become: false
      command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: idz_joinCMD

    - name: Copy join command to local file
      local_action: copy content="{{ idz_joinCMD.stdout_lines[0] }}" dest="./join-command"  

  handlers:
    - name: docker status
      service: name=docker state=started
    