IMAGE_NAME = "bento/ubuntu-20.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 3024
        v.cpus = 2
    end
      
    config.vm.define "Teomaz-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.3.17"
        master.vm.hostname = "Teomaz-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes/main.yml"
            ansible.extra_vars = {
                node_ip: "192.168.3.17",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.10.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes/node.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.10.#{i + 10}",
                }
            end
        end
    end
end